version: "3"
services:
    php:
        image: test-app/bitnami/php-fpm:8.3.4
        container_name: test-app.php
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                WWWUSER: '${WWWUSER}'
                WWWGROUP: '${WWWGROUP}'
        ports:
            - '8000:8000'
            - '5173:5173'
            - '8080:8080'
        volumes:
            - '.:/var/www/html'
